default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/dancemaker_development

production:
  <<: *default
  database: db/dancemaker_production

test: &test
  <<: *default
  database: db/dancemaker_test
